name: "Issue Labeler"
on:
  issues:
    types: [opened, edited]
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
    - uses: dequelabs/action-a11y-issue-labeler@main
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        include-title: 1
